--- 
version: '3.7'
services:
  watchtower:
    image: ghcr.io/containrrr/watchtower:latest
    container_name: watchtower
    env_file: stack.env # used by portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
#
#
networks:
  default:
    name: ${CONNET}
    external: true